openapi: 3.0.0
info:
  version: '2021-06-17'
  x-release: v4
  title: 'AWS IoT FleetWise #X Amz Target=IoTAutobahnControlPlane.AssociateVehicleFleet #X Amz Target=IoTAutobahnControlPlane.AssociateVehicleFleet #X Amz Target=IoTAutobahnControlPlane.GetSignalCatalog API'
  description: <p>Amazon Web Services IoT FleetWise is a fully managed service that you can use to collect, model, and transfer vehicle data to the Amazon Web Services cloud at scale. With Amazon Web Services IoT FleetWise, you can standardize all of your vehicle data models, independent of the in-vehicle communication architecture, and define data collection rules to transfer only high-value data to the cloud. </p> <p>For more information, see <a href="https://docs.aws.amazon.com/iot-fleetwise/latest/developerguide/">What is Amazon Web Services IoT FleetWise?</a> in the <i>Amazon Web Services IoT FleetWise Developer Guide</i>.</p>
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: iotfleetwise
  x-aws-signingName: iotfleetwise
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/iotfleetwise-2021-06-17.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://iotfleetwise.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS IoT FleetWise multi-region endpoint
- url: https://iotfleetwise.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS IoT FleetWise multi-region endpoint
- url: http://iotfleetwise.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS IoT FleetWise endpoint for China (Beijing) and China (Ningxia)
- url: https://iotfleetwise.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS IoT FleetWise endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=IoTAutobahnControlPlane.GetSignalCatalog'
paths:
  /#X-Amz-Target=IoTAutobahnControlPlane.GetSignalCatalog:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: GetSignalCatalog
      description: ' Retrieves information about a signal catalog. '
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSignalCatalogResponse'
        '480':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '481':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
        '482':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
        '483':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
        '484':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetSignalCatalogRequest'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - IoTAutobahnControlPlane.GetSignalCatalog
      summary: Amazon IoT FleetWise Get Signal Catalog
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=IoTAutobahnControlPlane.GetSignalCatalog'
components:
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
  schemas:
    InternalServerException: {}
    ThrottlingException: {}
    timestamp:
      type: string
      format: date-time
    arn:
      type: string
    GetSignalCatalogResponse:
      type: object
      required:
      - name
      - arn
      - creationTime
      - lastModificationTime
      properties:
        name:
          allOf:
          - $ref: '#/components/schemas/resourceName'
          - description: ' The name of the signal catalog. '
        arn:
          allOf:
          - $ref: '#/components/schemas/arn'
          - description: ' The Amazon Resource Name (ARN) of the signal catalog. '
        description:
          allOf:
          - $ref: '#/components/schemas/description'
          - description: ' A brief description of the signal catalog. '
        nodeCounts:
          allOf:
          - $ref: '#/components/schemas/NodeCounts'
          - description: ' The total number of network nodes specified in a signal catalog. '
        creationTime:
          allOf:
          - $ref: '#/components/schemas/timestamp'
          - description: ' The time the signal catalog was created in seconds since epoch (January 1, 1970 at midnight UTC time). '
        lastModificationTime:
          allOf:
          - $ref: '#/components/schemas/timestamp'
          - description: The last time the signal catalog was modified.
    description:
      type: string
      pattern: '[^\u0000-\u001F\u007F]+'
      minLength: 1
      maxLength: 2048
    ResourceNotFoundException: {}
    number:
      type: integer
    AccessDeniedException: {}
    resourceName:
      type: string
      pattern: '[a-zA-Z\d\-_:]+'
      minLength: 1
      maxLength: 100
    GetSignalCatalogRequest:
      type: object
      required:
      - name
      title: GetSignalCatalogRequest
      properties:
        name:
          allOf:
          - $ref: '#/components/schemas/resourceName'
          - description: ' The name of the signal catalog to retrieve information about. '
    ValidationException: {}
    NodeCounts:
      type: object
      properties:
        totalNodes:
          allOf:
          - $ref: '#/components/schemas/number'
          - description: The total number of nodes in a vehicle network.
        totalBranches:
          allOf:
          - $ref: '#/components/schemas/number'
          - description: The total number of nodes in a vehicle network that represent branches.
        totalSensors:
          allOf:
          - $ref: '#/components/schemas/number'
          - description: The total number of nodes in a vehicle network that represent sensors.
        totalAttributes:
          allOf:
          - $ref: '#/components/schemas/number'
          - description: The total number of nodes in a vehicle network that represent attributes.
        totalActuators:
          allOf:
          - $ref: '#/components/schemas/number'
          - description: The total number of nodes in a vehicle network that represent actuators.
      description: Information about the number of nodes and node types in a vehicle network.
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/iotfleetwise/
x-hasEquivalentPaths: true
